# Generated by Django 5.2.4 on 2025-10-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_alter_article_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
