# Generated by Django 5.2.4 on 2025-10-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_alter_article_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='banner_image',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
