# Generated by Django 5.2.4 on 2025-10-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_article_related_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='related_keywords',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
