# Generated by Django 5.2.4 on 2025-10-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0004_alter_article_related_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
