# Generated by Django 5.2.4 on 2025-10-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0004_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
