# Generated by Django 5.2.4 on 2025-11-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0005_remove_article_subcategory_delete_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='secondary_banner_image',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='secondary_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
