# Generated by Django 5.2.4 on 2025-10-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0007_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('breaking_news', 'Breaking News'), ('trending_now', 'Trending Now'), ('featured', 'Featured'), ('exclusive', 'Exclusive'), ('advertisement', 'Advertisement'), ('happening_now', 'Happening Now')], max_length=100, null=True),
        ),
    ]
